from app.routers.resoluciones import router as resoluciones_router
from app.routers.contratos import router as contratos_router
from app.routers.contratistas import router as contratistas_router
from app.routers.pagos import router as pagos_router
from app.routers.perfiles import router as perfiles_router
from app.routers.plantillas import router as plantillas_router
from app.routers.plantillas_objeto import router as plantillas_objeto_router
from app.routers.export import router as export_router
from app.routers.import_routes import router as import_router
from app.routers.actividades import router as actividades_router
from app.routers.supervisores import router as supervisores_router
from app.routers.inventario import router as inventario_router
from app.routers.auth import router as auth_router
from app.routers.usuarios import router as seguridad_router
from app.routers.evaluacion import router as evaluacion_router
from app.routers.documentos import router as documentos_router
